name:                symtegration
version:             0.1.0
github:              "chungyc/symtegration"
author:              "Yoo Chung"
maintainer:          "dev@chungyc.org"

extra-source-files:
- README.md
- docs/CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/chungyc/symtegration#readme>

language: GHC2021

default-extensions:
- OverloadedStrings

ghc-options:
- -Wall
- -Werror

dependencies:
- base >= 4.7 && < 5
- text >= 2 && < 2.2

library:
  source-dirs: src

tests:
  symtegration-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - symtegration
